name: qcs
channels: [conda-forge]
dependencies:
  - python=3.12
  - pinocchio>=3.4
  - mujoco
  - numpy
  - scipy
  - osqp
  - proxsuite
  - matplotlib
  - pyyaml
  - pytest
  - ruff
  - pip
  - pip:
      - robot_descriptions
      - -e .
